version: '3.1'

services:
# Если хотите подключить базу данных
  db:
# ВНИМАТЕЛЬНО! ВОТ ЭТО НАЗВАНИЕ СЕРВИСА - db - ДОЛЖНО БЫТЬ УКАЗАНО В БОТЕ КАК host В ПОДКЛЮЧЕНИИ К БАЗЕ ИЗ БОТА
# ТО ЕСТЬ НЕ АЙПИШНИК И НЕ ЛОКАЛХОСТ, А db
    container_name: database
    image: postgres
    env_file:
       - ./.env
    restart: unless-stopped
    ports:
      - 5432:5432
    networks:
      - botnet
    volumes:
      - postgres_data:/var/lib/postgresql/data/
  tgbot:
    container_name: bot
    build:
      context: .
      dockerfile: ./Dockerfile
      cache_from:
        - ghcr.io/hse-lab/bot:latest
    image: ghcr.io/hse-lab/bot:latest
#     command: sh ./start.sh
    networks:
      - botnet
    restart: always
    env_file:
      - ./.env
    volumes:
      - .:/src
    # Бот стартует после запуска базы
    ports:
      - "5000:5000"
    depends_on:
      - db

# указываются используемые сети
networks:
  botnet:
    # указывается драйвер сети
    driver: bridge
    
volumes:
  postgres_data:
