# This is a basic workflow to help you get started with Actions

name: CI


on:
  push:
    branches:
      - main

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Add environment variables to ..env!
        run: |
          echo DEBUG=0 >> .env
          echo ADMINS=${{ secrets.ADMINS }} >> .env
          echo BOT_TOKEN=${{ secrets.BOT_TOKEN }} >> .env
          echo ip=${{ secrets.ip }} >> .env
          echo POSTGRES_DB=${{ secrets.POSTGRES_DB }} >> .env
          echo POSTGRES_USER=${{ secrets.POSTGRES_USER }} >> .env
          echo POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }} >> .env
          echo POSTGRES_HOST=${{ secrets.POSTGRES_HOST }} >> .env
          echo POSTGRES_PORT=${{ secrets.POSTGRES_PORT }} >> .env
          
      - name: Build, Push and Deploy to Heroku #set the whatever name you want to this step
      
        uses: akhileshns/heroku-deploy@v3.12.12  # use the latest version of the action
        with:
          heroku_email: ${{ secrets.HEROKU_EMAIL }} # your heroku email
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }} # your  heroku api key
          heroku_app_name: "tb-bot-lab"
          docker_compose_file: './docker-compose.yml' # set the path to the folder where the docker-compose file is located
          
#           heroku_apps: '[{"imagename":"postgres","appname":"tg-bot-lab","apptype":"web"}]' # List of Docker Image name, Heroku app and Heroku app type
